import { AffordabilityPdfData } from "./types";

function formatCurrency(value: number) {
  return new Intl.NumberFormat("en-IN", {
    style: "currency",
    currency: "INR",
    maximumFractionDigits: 0,
  }).format(value);
}

export function buildAffordabilityReport(
  data: AffordabilityPdfData
): string {
  return `
==========================================
              RUPEEROAD
      ${data.title.toUpperCase()}
==========================================

Generated On
${data.generatedAt.toLocaleString("en-IN")}

------------------------------------------
INPUTS
------------------------------------------

Monthly Income : ${formatCurrency(data.monthlyIncome)}
Existing EMI   : ${formatCurrency(data.existingEmi)}
Down Payment   : ${formatCurrency(data.downPayment)}

------------------------------------------
RESULTS
------------------------------------------

Safe EMI       : ${formatCurrency(data.safeEmi)}
Maximum Loan   : ${formatCurrency(data.maxLoan)}
${data.assetLabel} : ${formatCurrency(data.assetPrice)}

Rating         : ${data.rating}

------------------------------------------
RECOMMENDATION
------------------------------------------

${data.recommendation}

==========================================
Generated by RupeeRoad
==========================================
`;
}